Ft milestone5
kbjude/ror-social-scaffold pull request #2
Opened 2020-06-18 17:23 UTC by kbjude

2020-06-19 04:15 UTC, Ispirett requested changes
# Status changes required
Hey @kbjude!  great job so far you are doing well :+1: 

There is some bugs :bug:   to take care of please see below.

- [ ]  Unless I am a friend with a user i should not be able to see their post.

- [ ]  When I click on all users while logged in i am greeted with this error.

`ArgumentError in UsersController#index
Unsupported argument type: true (TrueClass)`

2020-06-19 14:57 UTC, mosaaleb requested changes
#### Well done @kbjude :clap:

Nice job adding friendships feature in your models, but this milestone is incomplete. We need to add the ability to "send/receive" "accept/reject" requests to accept this milestone. 

Most requirements depend on adding friendships_controller and its actions and handling the views part (friendship buttons) send/accept/reject.

- [ ] User can invite friends

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png)

- [ ] User can see friendships requests

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png)

- [ ] There is a button to invite the user to friendship on users list page and on single-user page

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png)


- [ ] Remember to add integration tests for friendships (sending, accepting, rejecting) with Capybara.

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png)

- [ ] Add a short description for this pull request summarizing what's done.

Please handle these requirements and submit a new code review.

##### Muhammad Ebeid

2020-06-19 14:57 UTC, mosaaleb commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
- [ ] All associations, validations, and methods in user model needs to be tested.

2020-06-19 14:57 UTC, mosaaleb commented on spec/models/user_spec.rb
> +    #   visit 'users/new'
- [ ] Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history (screenshot from Pathwright)

2020-06-23 18:52 UTC, mosesogwo requested changes
**Hello! Good job... :+1:, a few changes are still required:**
:point_right: You should add a brief description to your PR
:point_right: After confirming a friendship, I could still send back another friend request and I'll have duplicate records in the db. This shouldn't happen.
:point_right: I can't access the single user page of other users when I'm logged in. It throws an error when I try to visit the url. Also, you should make user's names in the all users page link to their show page.
:point_right: You should organise your spec files properly into models and feature folders and add integration tests for friendship feature.
:point_right:  I can't find friend's posts on my timeline. My timeline should display both my posts and my friends' posts.


_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

2020-06-24 01:13 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @kbjude :lollipop: 

### Thank you for working on the changes requested by the previous reviewers :medal_sports: your project is working better with each iteration so you should feel very proud of your progress, :bar_chart:  please address to the following changes

#### Milestone 5

* [ ] There is a button to invite the user to friendship on users list page and on the single-user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

- The app only lets users invite other users to friendship on the list page but not on the single user page, let's work on this.

* [ ] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

- The app only shows the logged-in user posts but not their friends, let's also make this possible

#### General 

- [ ] Pull Request has meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

- This is usually a reason to invalidate a project so please make sure to add a short description in your pull request for your next submission and future projects (we cannot approve a project without it)

### That's it! :raised_hands: 

### Please :pray: make the changes :technologist: and submit for a code review when you are done :memo: 

Happy coding! :rocket: 

Any question? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-06-24 12:04 UTC, kbjude commented
All feedback from the TSE has been implemented.
- Having a message in to explain the PR
- Button appearing on the show page
- Being able to view messages of the friend by the logged-in user

2020-06-24 12:19 UTC, uryelah commented
Hi **Jude Kajura Balinda**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job with all the fixes from the last reviews!

About the PR message, next time write it at the top of the PR:
![Screenshot_2020-06-24 milestone to be merged to maste by kbjude · Pull Request #2 · kbjude ror-social-scaffold](https://user-images.githubusercontent.com/16193212/85554734-946fe000-b5fb-11ea-8c5a-b6d927da163a.png)
That's the place that should have the description. 

Also, remember to keep commits best practices next milestone:
- Capitalize your commits
- Use the imperative/present tense, not the past tense

-------

## **Your project is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**


---------

    
    
**Keep being an awesome dev and good luck with your next project!**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-06-24 13:02 UTC, merged